### ISSUE TITLE
Sprint 1 - Build/Test/Revise

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27316-IntoTheDeep#1]

**Comment by fistik12** [comment]
George: building intake system
Seto/Lucas: build drive train
Athisha/Michelle: forarm/claw

**Comment by fistik12** [comment]
![20241008_130723.jpg](https://github.com/user-attachments/assets/5a0cebd4-1868-4598-a5d1-61ffaa500d58)

![20241008_111950.jpg](https://github.com/user-attachments/assets/dc97dd66-da8b-4c74-9113-891cf5d86ea3)

![20241008_130718.jpg](https://github.com/user-attachments/assets/f730c925-b41a-4f75-a3d0-d7b4a62592d4)

![20241008_111946.jpg](https://github.com/user-attachments/assets/99850fed-777e-45fa-8007-1529487ae7c4)

So far, me and Lucas have started construction on the drive train. On the images, I have attached the motors to the structure. 

We plan on completing the side by the end of the week

**Comment by fistik12** [comment]
![20241009_142903.jpg](https://github.com/user-attachments/assets/f8f00368-2b41-48cb-92ea-7180270f5178)

Today, I was continuing my progress of the drive train. However I realized I was looking at the wrong instructions. Me and Lucas plan to work on the right instructions for tomorrow's class.

**Comment by PotatoesMashed** [comment]
![image](https://github.com/user-attachments/assets/fe713094-1ed1-4c55-9eed-c19149e75b86)
end of tuesday progress for intake

**Comment by PotatoesMashed** [comment]
![image](https://github.com/user-attachments/assets/aa5a3099-8bb6-43fe-82c9-86195ea3c73d)
end of wednesday progress for intake

**Comment by PotatoesMashed** [comment]
![image](https://github.com/user-attachments/assets/cb0460a7-6c18-4c35-b503-c5b98a5f31cd)
intake completed, starting work on tower assembly

**Comment by fistik12** [comment]
![20241010_130111.jpg](https://github.com/user-attachments/assets/2d15a93a-11d2-40de-b5f7-5c92a57223aa)

Now, me and Lucas have made half of the drive train, plan to finish it tomorrow

**Comment by fistik12** [comment]
Today, me and Lucas have completed the drive train assembly as planned.![20241011_142736.jpg](https://github.com/user-attachments/assets/f9e22f73-18dc-4bad-b2b3-407fbf92ae07)

We hope to make adjustments for Tuesday's class

**Comment by PotatoesMashed** [comment]
![image](https://github.com/user-attachments/assets/8c4e90e4-3cf1-43a6-8e7a-17b67793a705)
progress on tower assembly for tuesday.

**Comment by fistik12** [comment]
![20241015_130702.jpg](https://github.com/user-attachments/assets/49b079c4-3480-4b54-abe8-8d1175083187)

In today's class, we managed to assemble  the mecanum wheels to the drivetrain.

**Success**
Assembled mecanum wheels onto drivetrain (finally assembled using shaft collars).
Fastened onto shafts perfectly, no movement on wheels.


**Fails**
While turning the front 2 wheels, it feels stiff, potentially the moters or the shafts previously assembled.

**Comment by LucasN219** [comment]
Lucas Ng - Progress Log
https://docs.google.com/document/d/1Wj314F_QNNrxq9iuv9CPr726i3jMg0p0ziZMgJB-p4Y/edit?usp=sharing

**Comment by athishasurees** [comment]
Me and Michelle started to build the frame for the forearm/claw, and we got the base down. We also added the motor and the brackets the the frame and moved on to the next step.

![pic 1](https://github.com/user-attachments/assets/7437d85f-ace5-4c26-a77f-bf8f93dbe23a)
![pic 2](https://github.com/user-attachments/assets/80a3e122-aae2-43eb-adfd-7ad5861f1627)

**Comment by athishasurees** [comment]
Me and Michelle focused on the middle steps and we were trying to tighten and fix the parts from before. We made some mistakes along the way, but we caught them at the end when we were trying to put it all together. Sometimes we got frustrated but we powered through 

![pic 3](https://github.com/user-attachments/assets/39df4f2f-99bf-483f-bd42-31b55dd92670)
![pic 4](https://github.com/user-attachments/assets/8e86034d-8065-4c06-b821-d3121f7d2a10)

**Comment by athishasurees** [comment]
Me and Michelle finished the forearm/claw and we were very proud of ourselves. We made a lot of mistakes and most of our days were spent on trying to perfect the mistakes that we already made and were trying to fix, or we didn't understand what the instructions wanted us to do. 

![pic 5](https://github.com/user-attachments/assets/bd3429c2-3ef3-490a-a333-02b24ed96c71)
![pic 6](https://github.com/user-attachments/assets/e46f5519-0aa1-496a-a64c-4a146fd3920a)
