### ISSUE TITLE
Sprint 2 - Review and Demo

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27316-IntoTheDeep#12]

**Comment by athishasurees** [comment]
Successes: I successfully made the forearm/claw, even though it took longer than expected. I also helped with the assembly of all the parts together and got started on redoing the intake system

Failures: The forearm/claw took longer than expected and I wasn't sure how to properly build the intake arm with the longer extrustions so my group had to help me 

Next steps: Me and Michelle are going to be coding the arm using blocks. Hopefully we could get this done by the end of Sprint 3, but may need some time in Sprint 4.
