### ISSUE TITLE
Sprint 2 - Drivetrain Seto and Lucas

### ISSUE THREAD

**Issue by LucasN219** [sta-titansrobotics/27316-IntoTheDeep#13]
Sprint 2 - Drivetrain troubleshooting, adjustments and add-ons

**Comment by LucasN219** [comment]
Wednesday - Oct 16
Failures
- The wheels connected to the motor via chain are stiffer and turn slower
- One side was fixed by removing a 3mm spacer, but the other is still stiff

**Comment by fistik12** [comment]
![20241017_124420.jpg](https://github.com/user-attachments/assets/0e08b9b7-95a8-4c91-b494-620a0e26aff3)

Today, we managed to complete the drivetrain.

Success

**Comment by fistik12** [comment]
![20241018_155122.jpg](https://github.com/user-attachments/assets/4122bc1a-dea7-41c4-b3ed-465d23759c72)

![20241018_155004.jpg](https://github.com/user-attachments/assets/2b188ddb-c5d8-4031-a8b5-2b421f7f71f4)

![20241018_155007.jpg](https://github.com/user-attachments/assets/d493d424-7ed1-4123-85a0-d4d5e2fe4305)

**Comment by fistik12** [comment]
![20241022_153106.jpg](https://github.com/user-attachments/assets/df8f8e9b-1fe6-4bc1-8cb9-7ea3e4fe7fd5)

**Comment by LucasN219** [comment]
Wednesday, October 23
Intake system length fixture, assembly and basic wiring

Success
- Found the correct length for intake arm to reach the upper basket
- Attached the intake arm to the robot
- Basic wiring done with drive train motors

Failures/uncompleted
- Haven't connected wires to a control hub
- The front intake piece hasn't been connected to the intake arm
- Couldn't attach the cardboard to the arm
- Don't know if we can put samples into the upper basket, we have the height but haven't tested it with the code (we don't have code yet)

Tomorrow, I hope to be able to attach the cardboard and front intake piece to the robot
![IMG_4839](https://github.com/user-attachments/assets/f46c1d33-392f-46e7-9e85-708726ae951a)
![IMG_3839](https://github.com/user-attachments/assets/3de0c267-a310-46a0-a117-5e18e7707adc)

**Comment by fistik12** [comment]
![20241024_131031.jpg](https://github.com/user-attachments/assets/8ab57009-f8d3-4d67-a27e-ce014a789842)

**Comment by fistik12** [comment]
I have forgotten to take a picture today, but I managed to accomplish the following with the team:

1. Fixed cable management for the robot using materials such as zip-ties
2. Finalized the intake system for the robot, holds samples and can make it into the high basket

Next week, we plan on finalizing the robot by **adding the rev hub and battery**. In addition, we will **begin coding the movement of the wheels and arm**, hopefully **accomplishing it before the end of the month** (**Oct 31, 2024**)
