### ISSUE TITLE
Sprint 4:  Team Portfolio

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27316-IntoTheDeep#20]
PDF of Team Portfolio based on manual guidelines, with an emphasis on Think, Innovate and/or Control Award criteria.  Be sure review the [portfolio and award criteria  in the manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual-06)

Define and assign the distribution of duties here and create the necessary sub issues. Be sure to set the necessary assignees and label (Portfolio) on related issues.

**Comment by fistik12** [comment]
As of Nov 19, I have finalized the portfolio and have sent the files to the printer, mission complete!!!
